# Generated by Django 3.2.5 on 2021-08-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=75)),
                ('relationship', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('polarity', models.FloatField()),
                ('subjectivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EndorsementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=75)),
                ('relationship', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('polarity', models.FloatField()),
                ('subjectivity', models.FloatField()),
            ],
        ),
    ]
