# Generated by Django 4.0 on 2021-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=75)),
                ('relationship', models.CharField(max_length=75)),
                ('message', models.TextField()),
                ('polarity', models.FloatField()),
                ('subjectivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EndorsementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=75)),
                ('relationship', models.CharField(blank=True, max_length=75)),
                ('message', models.TextField(blank=True)),
                ('polarity', models.FloatField()),
                ('subjectivity', models.FloatField()),
                ('remote_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
