# Generated by Django 3.2.5 on 2021-08-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorsementrequest',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='endorsementrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='endorsementrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='endorsementrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='endorsementrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='endorsementrequest',
            name='relationship',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='endorsementrequest',
            name='role',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
